apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: peculio
  labels:
    app: peculio
    component: frontend
spec:
  selector:
    app: peculio
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
