apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: peculio-preview

commonLabels:
  environment: preview

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/10
        value:
          name: FRONTEND_URL
          value: "https://preview.peculio.cabrasky.net"
    target:
      kind: Deployment
      name: backend
